### ISSUE TITLE
rails がECS上で起動しない

### ISSUE THREAD

**Issue by Seiwa-Edu** [Seiwa-Edu/mesitero#58]
bundler: failed to load command: puma (/usr/local/bundle/bin/puma)

/usr/local/bundle/gems/puma-5.6.1/lib/puma/dsl.rb:83:in `read': No such file or directory @ rb_sysopen - config/puma.rb (Errno::ENOENT)

from /usr/local/bundle/gems/puma-5.6.1/lib/puma/dsl.rb:83:in `_load_from'

**Comment by Seiwa-Edu** [comment]
◆想定される原因
・インスタンスが Drainの状態になっている
クラスターからコンテナインスタンスを削除する必要がある場合があります。たとえば、システム更新を実行する、Docker デーモンを更新する、またはクラスターサイズを縮小する場合などです。Amazon ECS では、コンテナインスタンスをDRAINING ステータスに遷移する能力を提供します。

参考：
https://docs.aws.amazon.com/ja_jp/AmazonECS/latest/developerguide/container-instance-draining.html
